### ISSUE TITLE
Add Weekly total

### ISSUE THREAD

**Issue by mcwhittemore** [vees/toggl2ps#5]

**Comment by jordanhaven** [comment]
bump. why close this? we still haven't seen this added. +1. @vees pls respond

**Comment by mcwhittemore** [comment]
@jordanhaven - I'm going through and closing issues that I own that haven't seen traffic in a long time. If this is still in active development, can someone open a new ticket and keep this one closed.

**Comment by jordanhaven** [comment]
I'm just messing with you, bro 👍

**Comment by mcwhittemore** [comment]
:(
